import re
import logging
import textstat
from typing import Dict, Any
import json

from .base_agent import BaseAgent

logger = logging.getLogger(__name__)

class AIContentAgent(BaseAgent):
    """Agent for detecting AI-generated content."""
    
    def __init__(self):
        super().__init__("AIContentAgent")
        self.ai_indicators = self._load_ai_indicators()
    
    def analyze(self, text: str, api_keys: Dict[str, str]) -> Dict[str, Any]:
        """Analyze text for AI-generated content."""
        
        # Try API-based detection first
        api_result = self._try_api_detection(text, api_keys)
        if api_result:
            return api_result
        
        # Fallback to local heuristic detection
        return self._local_ai_detection(text)
    
    def _try_api_detection(self, text: str, api_keys: Dict[str, str]) -> Dict[str, Any]:
        """Try API-based AI detection."""
        
        # Method 1: Gemini API (if available)
        if api_keys.get('gemini_api_key'):
            try:
                return self._gemini_detection(text, api_keys['gemini_api_key'])
            except Exception as e:
                logger.warning(f"Gemini API detection failed: {e}")
        
        return None
    
    def _gemini_detection(self, text: str, api_key: str) -> Dict[str, Any]:
        """Use Gemini API for AI content detection."""
        
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={api_key}"
        
        prompt = f"""Analyze the following text and determine if it was likely generated by AI. 
        Look for patterns like:
        - Overly perfect grammar and structure
        - Repetitive phrasing
        - Lack of personal voice or opinion
        - Generic academic language
        
        Text to analyze:
        {text[:2000]}
        
        Respond with a JSON object containing:
        - "ai_probability": a number from 0-100 indicating likelihood of AI generation
        - "confidence": confidence in the assessment (0-10)
        - "indicators": list of specific indicators found
        """
        
        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }]
        }
        
        try:
            response = self._make_api_request(url, json_data=payload)
            
            # Parse Gemini response
            content = response['candidates'][0]['content']['parts'][0]['text']
            
            # Extract JSON from response (basic parsing)
            try:
                json_match = re.search(r'\{.*\}', content, re.DOTALL)
                if json_match:
                    result_data = json.loads(json_match.group())
                    return {
                        'percentage': result_data.get('ai_probability', 0),
                        'confidence': result_data.get('confidence', 5),
                        'indicators': result_data.get('indicators', []),
                        'method': 'gemini_api'
                    }
            except json.JSONDecodeError:
                pass
            
            # Fallback parsing
            return self._parse_gemini_text_response(content)
            
        except Exception as e:
            logger.error(f"Gemini API error: {e}")
            raise
    
    def _local_ai_detection(self, text: str) -> Dict[str, Any]:
        """Local heuristic AI content detection."""
        
        score = 0.0
        indicators = []
        
        # 1. Check readability (AI often produces very readable text)
        flesch_score = textstat.flesch_reading_ease(text)
        if 60 <= flesch_score <= 80:  # Sweet spot for AI
            score += 15
            indicators.append("Optimal readability score typical of AI")
        
        # 2. Check for AI-typical patterns
        ai_patterns = [
            (r'\b(furthermore|moreover|additionally|consequently)\b', "Overuse of transition words"),
            (r'\b(it is important to note|it should be noted)\b', "AI-typical hedging phrases"),
            (r'\b(in conclusion|to summarize|in summary)\b', "Formulaic conclusion patterns"),
            (r'\b(comprehensive|robust|significant|substantial)\b', "Overuse of emphasis words")
        ]
        
        for pattern, description in ai_patterns:
            matches = len(re.findall(pattern, text, re.IGNORECASE))
            if matches > 3:
                score += matches * 3
                indicators.append(f"{description} ({matches} instances)")
        
        # 3. Check sentence structure consistency
        sentences = [s.strip() for s in text.split('.') if len(s.strip()) > 10]
        if len(sentences) > 5:
            lengths = [len(s.split()) for s in sentences]
            avg_length = sum(lengths) / len(lengths)
            
            # AI tends to produce very consistent sentence lengths
            variance = sum((l - avg_length) ** 2 for l in lengths) / len(lengths)
            if variance < avg_length / 3:  # Low variance
                score += 10
                indicators.append("Suspiciously consistent sentence lengths")
        
        # 4. Check for lack of personal voice
        personal_indicators = ['I think', 'in my opinion', 'I believe', 'personally', 'my experience']
        personal_count = sum(text.lower().count(phrase) for phrase in personal_indicators)
        
        if len(text) > 1000 and personal_count == 0:
            score += 8
            indicators.append("Complete lack of personal voice or opinion")
        
        # 5. Perfect grammar check (very basic)
        grammar_errors = self._count_basic_grammar_errors(text)
        if len(text) > 500 and grammar_errors == 0:
            score += 5
            indicators.append("Suspiciously perfect grammar")
        
        # Normalize score to percentage
        percentage = min(100, max(0, score))
        
        percentage = max(0, percentage)
        
        return {
            'percentage': round(percentage, 1),
            'confidence': min(10, len(indicators) + 3),
            'indicators': indicators,
            'method': 'local_heuristic'
        }
    
    def _count_basic_grammar_errors(self, text: str) -> int:
        """Count basic grammar errors (very simplified)."""
        errors = 0
        
        # Check for double spaces
        errors += len(re.findall(r'  +', text))
        
        # Check for missing capitalization after periods
        errors += len(re.findall(r'\. [a-z]', text))
        
        # Check for basic punctuation errors
        errors += len(re.findall(r'[a-zA-Z],[a-zA-Z]', text))  # Missing space after comma
        
        return errors
    
    def _parse_gemini_text_response(self, content: str) -> Dict[str, Any]:
        """Parse Gemini text response when JSON parsing fails."""
        
        # Look for probability mentions
        prob_match = re.search(r'(\d+)%?.*?(probability|likely|chance)', content, re.IGNORECASE)
        probability = 0
        
        if prob_match:
            probability = int(prob_match.group(1))
        
        # Look for confidence mentions
        conf_match = re.search(r'confidence.*?(\d+)', content, re.IGNORECASE)
        confidence = 5  # Default
        
        if conf_match:
            confidence = int(conf_match.group(1))
        
        return {
            'percentage': probability,
            'confidence': confidence,
            'indicators': ['Gemini API analysis'],
            'method': 'gemini_text_parsing'
        }
    
    def _load_ai_indicators(self) -> Dict[str, Any]:
        """Load AI content indicators."""
        return {
            'transition_overuse': ['furthermore', 'moreover', 'additionally', 'consequently'],
            'hedging_phrases': ['it is important to note', 'it should be noted'],
            'emphasis_words': ['comprehensive', 'robust', 'significant', 'substantial'],
            'formulaic_phrases': ['in conclusion', 'to summarize', 'in summary']
        }
